### ISSUE TITLE
subdomainbrute模块问题

### ISSUE THREAD

**Issue by CBH-DOG** [Cl0udG0d/HXnineTails#14]
运行了subdomainbruteMain.py发现报错，无法找到dict\subnames.txt之类的。然后我独立运行subdomainbrute.py程序是正常运行的。这个情况是怎么回事，用os.system执行命令  和subdomainbrute工具下执行命令为什么结果会不一样呀？这样导致系统的 -s 功能会少subdomainbrute功能。这是运行subdomainbruteMain.py模块报的错误 求大佬康康
Traceback (most recent call last):
  File "D:\bysj\HXnineTails\subDomainsBrute\subDomainsBrute-master\subDomainsBrute.py", line 46, in <module>
    dns_servers = load_dns_servers()
  File "D:\bysj\HXnineTails\subDomainsBrute\subDomainsBrute-master\lib\common_py3.py", line 42, in load_dns_servers
    for server in open('dict/dns_servers.txt').readlines():
FileNotFoundError: [Errno 2] No such file or directory: 'dict/dns_servers.txt'

**Comment by Throokie** [comment]
请在config.py下检查下您的subdomainbruteMain路径，可能是路径不正常原因导致的
![image](https://user-images.githubusercontent.com/58783886/118372754-b1cbe500-b5e5-11eb-866e-cd89fc294c25.png)
